words = input("Enter words separated by space: ").split()
longest_word = max(words, key=len)
length = len(longest_word)
print("The longest word is:", longest_word)
print("Length of the longest word:", length)
